### PR TITLE
Revert "Bump htmlunit from 2.67.0 to 2.68.0"

### PR DESCRIPTION
**Pull request by NotMyFault**
Reverts jenkinsci/jenkins-test-harness-htmlunit#94

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]
Thanks for the fast response!

**Comment by NotMyFault** [comment]
@Vlatombe I had a chat with the maintainer of HtmlUnit ealier, they will cut a release tomorrow, which contains https://github.com/HtmlUnit/htmlunit/commit/c1028b0bbf180acdab934cd9b8a3a466f52bd249 to fix the xerces detection regression.

Do you think we can update to 2.69.0 once released?

**Comment by Vlatombe** [comment]
> Do you think we can update to 2.69.0 once released?

Check running `jenkins-test` module against it.

**Comment by jglick** [comment]
Now #97 ⇒ https://github.com/jenkinsci/jenkins-test-harness/pull/545.

**Pull request merged**
